[Grupa 1] Maciej Gryszkiewicz PD2
mini-pw/2021L-WUM pull request #116
Opened 2021-03-26 11:06 UTC by mgryszkiewicz

2021-03-26 11:17 UTC, mgryszkiewicz commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>Tu oczywiście powinno być BinaryEncoding.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p><strong>Super, że zwrócono na to uwagę!</strong></p><p>Ciekawe byłoby zobaczyć ile było wartości unikalnych przed i po tej operacji.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>To prawda :) </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>Błąd należałoby wyliczyć tylko dla wartości imputowanych, bo gdy wyliczamy dla całej kolumny wynik jest zakłamany, ponieważ we wzorze jest wyliczana średnia, przez co liczność ma znaczenie.</p><p> </p><p>Prośba o zmodyfikowanie sposobu wyliczania błędu.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='28'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>warto byłoby także wyliczyć średnią</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>Ten wykres jest mało informatywny, znacznie lepszy jest boxplot poniżej</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='34'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>brakuje średniej</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>jak przy analogicznym wykresie wyżej</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>analogiczna uwaga jak wyżej</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2021-03-27 19:00 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa2/Gryszkiewicz_Maciej/PD2_Gryszkiewicz_Maciej.ipynb
> +{
<p>Dobrze, że wartości odchyleń standardowych odniesiono do wielkości statystyk opisujących dane w kolumnach :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/116/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='48'/>

2021-03-27 19:02 UTC, ptomaszewska requested changes
Dobrze wykonana praca domowa - super, że wykonano normalizację danych tekstowych przed encoding'iem. 

Prośba o poprawę sposobu wyliczenia błędu przy imputacji

2021-03-27 20:27 UTC, merged