Zolkowski Artur PD1
mini-pw/2021L-WUM pull request #25
Opened 2021-03-09 12:29 UTC by arturzolkowski

2021-03-30 09:46 UTC, Gizzio commented on Prace_domowe/Praca_domowa1/Grupa3/artur_zolkowski/pd1.ipynb
> +{
<p>W pdfie chyba brakuje tego wykresu</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/25/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2021-03-30 10:45 UTC, Gizzio requested changes
Brakuje wykresów w PDFie chyba

2021-03-30 22:20 UTC, arturzolkowski commented on Prace_domowe/Praca_domowa1/Grupa3/artur_zolkowski/pd1.ipynb
> +{
Podmieniłem plik pdf, teraz wszystko powinno być ok

2021-04-27 07:18 UTC, Gizzio approved these changes
W [8] korelacja dla X i Y tylko zaszumia obraz (niepotrzebna)
Tak samo w [10] -- tutaj już w ogóle mało widać. 
Ogólnie ploty względem area i rain bardzo mało mówią, te zmienne należy zlogarytmowąć przed plotowaniem (i powinieneś to zauważyć po pierwszym plocie [7])
Na plocie [12] brakuje liczb - ale fajnie że jest.
Na [13,14] możnaby na jednym plocie pokazać też wariancję (coś jak tu https://seaborn.pydata.org/_images/lineplot_11_0.png)
W ogóle mało eksploracji wariancji jednej zmiennej względem drugiej. 

Ocena: -1 (względem max)

2021-04-27 07:19 UTC, merged