[Grupa 1] Praca Domowa 1 Maciej Chylak
mini-pw/2021L-WUM pull request #37
Opened 2021-03-11 14:24 UTC by maciekchylak

2021-03-12 21:48 UTC, ptomaszewska requested changes
Z uwagi na to, że niedawno pojawił się w ramach githuba nowy tool do sprawdzania i komentowania Jupyter Notebook - ReviewNB, byłoby mi łatwiej gdyby wrzucony notebook miał widoczne output'y. Prośba o wrzucenie takiej wersji. Na razie bowiem w tym narzędziu nie ma możliwości wykonywania komórek kodu, a pobranie kodu lokalnie jest możliwe ale zajmuje trochę czasu bo trzeba robić nowy branch itp.

2021-03-13 11:08 UTC, maciekchylak reviewed
Już pozmieniałem, outputy powinny się pojawić

2021-03-13 20:59 UTC, ptomaszewska commented
Dziękuję - rzeczywiście teraz outputy są widoczne.

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Doceniam, że zautomatyzowano pobieranie danych.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Nie mamy w danych szeregu czasowego, dlatego taka wizualizacja jest mało informatywna - istnieją lepsze metody wizualizacji (odnosi się to także do wykresu poniżej).</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Bardzo dobry pomysł aby wykorzystać informację przestrzenną w danych - tak właśnie należało postąpić.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Super, że pseudomapę ilustrującą średnią uzupełniono o drugą ilustrującą liczbę rekordów w danym regionie - w ten sposób mamy bardziej kompleksowy ogląd sytuacji. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Wartościowa obserwacja :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Fajny pomysł :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='23'/>

2021-03-13 21:25 UTC, ptomaszewska commented on Prace_domowe/Praca_domowa1/Grupa1/Maciej_Chylak/PD1_Maciej_Chylak.ipynb
> +{
<p>Super, że posortowano miesiące tak aby odpowiadały kalendarzowi. Wykres liniowy jest trochę dyskusyjny bo nie wiadomo co się dzieje pomiędzy punktami, które mamy w danych. Można ten wykres potraktować jako akceptowalny bo zastosował Pan linie wraz z oznaczeniami punktowymi, które sygnalizujące dane. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mini-pw/2021L-WUM/pull/37/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='27'/>

2021-03-13 21:36 UTC, merged