Hubert_Ruczynski_PD1
mini-pw/2021L-WUM pull request #8
Opened 2021-03-08 12:18 UTC by HubertR21

2021-03-23 11:07 UTC, HubertR21 commented
Dodaje PD2 do poprzedniego pull'a, bo nie został wmergowany.

2021-03-30 10:44 UTC, Gizzio requested changes
Rozbij na 2 PRy jak możesz

2021-03-31 10:36 UTC, HubertR21 commented
Nie mam pojęcia jak to zrobić. Mógłbyś mi jakoś pomóc?

2021-04-27 07:22 UTC, Gizzio commented
Chyba wszystko jest w innych PRach.

2021-04-27 07:22 UTC, closed without merging

2021-04-27 07:26 UTC, HubertR21 commented
Tak, ten PR to ten zepsuty, już wrzuciłem PD2 osobno jak wmergowałeś PD1